CREATE TABLE funds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    symbol TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    fund_type TEXT NOT NULL,
    manager TEXT,
    inception_date DATE,
    expense_ratio NUMERIC,
    aum NUMERIC,
    nav NUMERIC,
    previous_nav NUMERIC,
    change_percent NUMERIC,
    performance_1m NUMERIC,
    performance_3m NUMERIC,
    performance_6m NUMERIC,
    performance_1y NUMERIC,
    performance_ytd NUMERIC,
    risk_score NUMERIC,
    category TEXT,
    currency TEXT DEFAULT 'TRY',
    last_updated TIMESTAMP DEFAULT NOW(),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW()
);